// <auto-generated />
using System;
using Bookman.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bookman.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20220309172344_ForReal")]
    partial class ForReal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Bookman.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassificationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pages")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ClassificationId");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Victor Hugo",
                            CategoryId = 1,
                            ClassificationId = 1,
                            ISBN = "978-0451419439",
                            Pages = 1488,
                            Price = 9.9499999999999993,
                            Publisher = "Signet",
                            Title = "Les Miserables"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Doris Kearns Goodwin",
                            CategoryId = 2,
                            ClassificationId = 2,
                            ISBN = "978-0743270755",
                            Pages = 944,
                            Price = 14.58,
                            Publisher = "Simon & Schuster",
                            Title = "Team of Rivals"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Alice Schroeder",
                            CategoryId = 2,
                            ClassificationId = 2,
                            ISBN = "978-0553384611",
                            Pages = 832,
                            Price = 21.539999999999999,
                            Publisher = "Bantam",
                            Title = "The Snowball"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Ronald C. White",
                            CategoryId = 2,
                            ClassificationId = 2,
                            ISBN = "978-0812981254",
                            Pages = 864,
                            Price = 11.609999999999999,
                            Publisher = "Random House",
                            Title = "American Ulysses"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Laura Hillenbrand",
                            CategoryId = 3,
                            ClassificationId = 2,
                            ISBN = "978-0812974492",
                            Pages = 528,
                            Price = 13.33,
                            Publisher = "Random House",
                            Title = "Unbroken"
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Michael Crichton",
                            CategoryId = 3,
                            ClassificationId = 1,
                            ISBN = "978-0804171281",
                            Pages = 288,
                            Price = 13.33,
                            Publisher = "Random House",
                            Title = "The Great Train Robbery"
                        },
                        new
                        {
                            BookId = 7,
                            Author = "Cal Newport",
                            CategoryId = 4,
                            ClassificationId = 2,
                            ISBN = "978-1455586691",
                            Pages = 304,
                            Price = 14.99,
                            Publisher = "Vintage",
                            Title = "Deep Work"
                        },
                        new
                        {
                            BookId = 8,
                            Author = "Michael Abrashoff",
                            CategoryId = 4,
                            ClassificationId = 2,
                            ISBN = "978-1455523023",
                            Pages = 240,
                            Price = 21.66,
                            Publisher = "Grand Central Publishing",
                            Title = "It's Your Ship"
                        },
                        new
                        {
                            BookId = 9,
                            Author = "Richard Branson",
                            CategoryId = 5,
                            ClassificationId = 2,
                            ISBN = "978-1591847984",
                            Pages = 400,
                            Price = 29.16,
                            Publisher = "Grand Central Publishing",
                            Title = "The Virgin Way"
                        },
                        new
                        {
                            BookId = 10,
                            Author = "John Grisham",
                            CategoryId = 6,
                            ClassificationId = 1,
                            ISBN = "978-0553393613",
                            Pages = 642,
                            Price = 15.029999999999999,
                            Publisher = "Batnam",
                            Title = "Sycamore Row"
                        },
                        new
                        {
                            BookId = 11,
                            Author = "Mike Rowe",
                            CategoryId = 3,
                            ClassificationId = 1,
                            ISBN = "978-1982131470",
                            Pages = 272,
                            Price = 12.300000000000001,
                            Publisher = "Gallery Books",
                            Title = "The Way I Heard It"
                        },
                        new
                        {
                            BookId = 12,
                            Author = "Unisses S. Grant",
                            CategoryId = 2,
                            ClassificationId = 2,
                            ISBN = "978-1481216043",
                            Pages = 552,
                            Price = 19.989999999999998,
                            Publisher = "CreateSpace Independent Publishing Platform",
                            Title = "The Complete Personal Memoirs of Ulysses S. Grant"
                        },
                        new
                        {
                            BookId = 13,
                            Author = "C.S. Lewis",
                            CategoryId = 7,
                            ClassificationId = 1,
                            ISBN = "978-0060652937",
                            Pages = 209,
                            Price = 10.27,
                            Publisher = "HarperOne",
                            Title = "The Screwtape Letters"
                        },
                        new
                        {
                            BookId = 14,
                            Author = "Shawn Stevenson",
                            CategoryId = 8,
                            ClassificationId = 2,
                            ISBN = "978-1623367398",
                            Pages = 288,
                            Price = 17.59,
                            Publisher = "Rodale Books",
                            Title = "Sleep Smarter"
                        },
                        new
                        {
                            BookId = 15,
                            Author = "Ron Chernow",
                            CategoryId = 2,
                            ClassificationId = 2,
                            ISBN = "978-1400077304",
                            Pages = 832,
                            Price = 16.59,
                            Publisher = "Vintage",
                            Title = "Titan"
                        },
                        new
                        {
                            BookId = 16,
                            Author = "Tom Clancy",
                            CategoryId = 9,
                            ClassificationId = 1,
                            ISBN = "978-0440001027",
                            Pages = 656,
                            Price = 9.9900000000000002,
                            Publisher = "Berkley",
                            Title = "The Hunt for Red October"
                        });
                });

            modelBuilder.Entity("Bookman.Models.CartLineItem", b =>
                {
                    b.Property<int>("LineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("LineID");

                    b.HasIndex("BookId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("CartLineItem");
                });

            modelBuilder.Entity("Bookman.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Classic"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Biography"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Historical"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Self-Help"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Business"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Thriller"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Christian"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Health"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Action"
                        });
                });

            modelBuilder.Entity("Bookman.Models.Classification", b =>
                {
                    b.Property<int>("ClassificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassificationName")
                        .HasColumnType("TEXT");

                    b.HasKey("ClassificationId");

                    b.ToTable("Classification");

                    b.HasData(
                        new
                        {
                            ClassificationId = 1,
                            ClassificationName = "Fiction"
                        },
                        new
                        {
                            ClassificationId = 2,
                            ClassificationName = "Non-Fiction"
                        });
                });

            modelBuilder.Entity("Bookman.Models.Purchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Shipped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Zipcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PurchaseId");

                    b.ToTable("Purchase");
                });

            modelBuilder.Entity("Bookman.Models.Book", b =>
                {
                    b.HasOne("Bookman.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookman.Models.Classification", "Classification")
                        .WithMany()
                        .HasForeignKey("ClassificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookman.Models.CartLineItem", b =>
                {
                    b.HasOne("Bookman.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId");

                    b.HasOne("Bookman.Models.Purchase", null)
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseId");
                });
#pragma warning restore 612, 618
        }
    }
}
